import { Comuna } from '../../components/comuna/entities/comuna.entity';

export const comunaSeedData: Partial<Comuna>[] = [
  // Región de Tarapacá (1)
  { comunaId: 1, nombre: 'Iquique', regionId: 1 },
  { comunaId: 2, nombre: 'Alto Hospicio', regionId: 1 },
  { comunaId: 3, nombre: 'Pozo Almonte', regionId: 1 },
  { comunaId: 4, nombre: 'Camiña', regionId: 1 },
  { comunaId: 5, nombre: 'Colchane', regionId: 1 },
  { comunaId: 6, nombre: 'Huara', regionId: 1 },
  { comunaId: 7, nombre: 'Pica', regionId: 1 },

  // Región de Antofagasta (2)
  { comunaId: 8, nombre: 'Antofagasta', regionId: 2 },
  { comunaId: 9, nombre: 'Mejillones', regionId: 2 },
  { comunaId: 10, nombre: 'Sierra Gorda', regionId: 2 },
  { comunaId: 11, nombre: 'Taltal', regionId: 2 },
  { comunaId: 12, nombre: 'Calama', regionId: 2 },
  { comunaId: 13, nombre: 'Ollagüe', regionId: 2 },
  { comunaId: 14, nombre: 'San Pedro de Atacama', regionId: 2 },

  // Región de Atacama (3)
  { comunaId: 15, nombre: 'Copiapó', regionId: 3 },
  { comunaId: 16, nombre: 'Caldera', regionId: 3 },
  { comunaId: 17, nombre: 'Tierra Amarilla', regionId: 3 },
  { comunaId: 18, nombre: 'Chañaral', regionId: 3 },
  { comunaId: 19, nombre: 'Diego de Almagro', regionId: 3 },
  { comunaId: 20, nombre: 'Vallenar', regionId: 3 },
  { comunaId: 21, nombre: 'Freirina', regionId: 3 },
  { comunaId: 22, nombre: 'Huasco', regionId: 3 },
  { comunaId: 23, nombre: 'Alto del Carmen', regionId: 3 },

  // Región de Coquimbo (4)
  { comunaId: 24, nombre: 'La Serena', regionId: 4 },
  { comunaId: 25, nombre: 'Coquimbo', regionId: 4 },
  { comunaId: 26, nombre: 'Andacollo', regionId: 4 },
  { comunaId: 27, nombre: 'La Higuera', regionId: 4 },
  { comunaId: 28, nombre: 'Paihuano', regionId: 4 },
  { comunaId: 29, nombre: 'Vicuña', regionId: 4 },
  { comunaId: 30, nombre: 'Illapel', regionId: 4 },
  { comunaId: 31, nombre: 'Canela', regionId: 4 },
  { comunaId: 32, nombre: 'Los Vilos', regionId: 4 },
  { comunaId: 33, nombre: 'Salamanca', regionId: 4 },
  { comunaId: 34, nombre: 'Ovalle', regionId: 4 },
  { comunaId: 35, nombre: 'Combarbalá', regionId: 4 },
  { comunaId: 36, nombre: 'Monte Patria', regionId: 4 },
  { comunaId: 37, nombre: 'Punitaqui', regionId: 4 },
  { comunaId: 38, nombre: 'Río Hurtado', regionId: 4 },

  // Región de Valparaíso (5)
  { comunaId: 39, nombre: 'Valparaíso', regionId: 5 },
  { comunaId: 40, nombre: 'Casablanca', regionId: 5 },
  { comunaId: 41, nombre: 'Concón', regionId: 5 },
  { comunaId: 42, nombre: 'Juan Fernández', regionId: 5 },
  { comunaId: 43, nombre: 'Puchuncaví', regionId: 5 },
  { comunaId: 44, nombre: 'Quintero', regionId: 5 },
  { comunaId: 45, nombre: 'Viña del Mar', regionId: 5 },
  { comunaId: 46, nombre: 'Isla de Pascua', regionId: 5 },
  { comunaId: 47, nombre: 'Los Andes', regionId: 5 },
  { comunaId: 48, nombre: 'Calle Larga', regionId: 5 },
  { comunaId: 49, nombre: 'Rinconada', regionId: 5 },
  { comunaId: 50, nombre: 'San Esteban', regionId: 5 },
  { comunaId: 51, nombre: 'La Ligua', regionId: 5 },
  { comunaId: 52, nombre: 'Cabildo', regionId: 5 },
  { comunaId: 53, nombre: 'Papudo', regionId: 5 },
  { comunaId: 54, nombre: 'Petorca', regionId: 5 },
  { comunaId: 55, nombre: 'Zapallar', regionId: 5 },
  { comunaId: 56, nombre: 'Quillota', regionId: 5 },
  { comunaId: 57, nombre: 'Calera', regionId: 5 },
  { comunaId: 58, nombre: 'Hijuelas', regionId: 5 },
  { comunaId: 59, nombre: 'La Cruz', regionId: 5 },
  { comunaId: 60, nombre: 'Nogales', regionId: 5 },
  { comunaId: 61, nombre: 'San Antonio', regionId: 5 },
  { comunaId: 62, nombre: 'Algarrobo', regionId: 5 },
  { comunaId: 63, nombre: 'Cartagena', regionId: 5 },
  { comunaId: 64, nombre: 'El Quisco', regionId: 5 },
  { comunaId: 65, nombre: 'El Tabo', regionId: 5 },
  { comunaId: 66, nombre: 'San Sebastián', regionId: 5 },
  { comunaId: 67, nombre: 'Villa Alemana', regionId: 5 },
  { comunaId: 68, nombre: 'Limache', regionId: 5 },
  { comunaId: 69, nombre: 'Olmué', regionId: 5 },
  { comunaId: 70, nombre: 'Quilpué', regionId: 5 },

  // Región del Libertador General Bernardo O'Higgins (6)
  { comunaId: 71, nombre: 'Rancagua', regionId: 6 },
  { comunaId: 72, nombre: 'Codegua', regionId: 6 },
  { comunaId: 73, nombre: 'Coinco', regionId: 6 },
  { comunaId: 74, nombre: 'Coltauco', regionId: 6 },
  { comunaId: 75, nombre: 'Doñihue', regionId: 6 },
  { comunaId: 76, nombre: 'Graneros', regionId: 6 },
  { comunaId: 77, nombre: 'Las Cabras', regionId: 6 },
  { comunaId: 78, nombre: 'Machalí', regionId: 6 },
  { comunaId: 79, nombre: 'Malloa', regionId: 6 },
  { comunaId: 80, nombre: 'Mostazal', regionId: 6 },
  { comunaId: 81, nombre: 'Olivar', regionId: 6 },
  { comunaId: 82, nombre: 'Peumo', regionId: 6 },
  { comunaId: 83, nombre: 'Pichidegua', regionId: 6 },
  { comunaId: 84, nombre: 'Quinta de Tilcoco', regionId: 6 },
  { comunaId: 85, nombre: 'Rengo', regionId: 6 },
  { comunaId: 86, nombre: 'Requínoa', regionId: 6 },
  { comunaId: 87, nombre: 'San Vicente', regionId: 6 },
  { comunaId: 88, nombre: 'Pichilemu', regionId: 6 },
  { comunaId: 89, nombre: 'La Estrella', regionId: 6 },
  { comunaId: 90, nombre: 'Litueche', regionId: 6 },
  { comunaId: 91, nombre: 'Marchihue', regionId: 6 },
  { comunaId: 92, nombre: 'Navidad', regionId: 6 },
  { comunaId: 93, nombre: 'Paredones', regionId: 6 },
  { comunaId: 94, nombre: 'San Fernando', regionId: 6 },
  { comunaId: 95, nombre: 'Chépica', regionId: 6 },
  { comunaId: 96, nombre: 'Chimbarongo', regionId: 6 },
  { comunaId: 97, nombre: 'Lolol', regionId: 6 },
  { comunaId: 98, nombre: 'Nancagua', regionId: 6 },
  { comunaId: 99, nombre: 'Palmilla', regionId: 6 },
  { comunaId: 100, nombre: 'Peralillo', regionId: 6 },
  { comunaId: 101, nombre: 'Placilla', regionId: 6 },
  { comunaId: 102, nombre: 'Pumanque', regionId: 6 },
  { comunaId: 103, nombre: 'Santa Cruz', regionId: 6 },

  // Región del Maule (7)
  { comunaId: 104, nombre: 'Talca', regionId: 7 },
  { comunaId: 105, nombre: 'Constitución', regionId: 7 },
  { comunaId: 106, nombre: 'Curepto', regionId: 7 },
  { comunaId: 107, nombre: 'Empedrado', regionId: 7 },
  { comunaId: 108, nombre: 'Maule', regionId: 7 },
  { comunaId: 109, nombre: 'Pelarco', regionId: 7 },
  { comunaId: 110, nombre: 'Pencahue', regionId: 7 },
  { comunaId: 111, nombre: 'Río Claro', regionId: 7 },
  { comunaId: 112, nombre: 'San Clemente', regionId: 7 },
  { comunaId: 113, nombre: 'San Rafael', regionId: 7 },
  { comunaId: 114, nombre: 'Cauquenes', regionId: 7 },
  { comunaId: 115, nombre: 'Chanco', regionId: 7 },
  { comunaId: 116, nombre: 'Pelluhue', regionId: 7 },
  { comunaId: 117, nombre: 'Curicó', regionId: 7 },
  { comunaId: 118, nombre: 'Hualañé', regionId: 7 },
  { comunaId: 119, nombre: 'Licantén', regionId: 7 },
  { comunaId: 120, nombre: 'Molina', regionId: 7 },
  { comunaId: 121, nombre: 'Rauco', regionId: 7 },
  { comunaId: 122, nombre: 'Romeral', regionId: 7 },
  { comunaId: 123, nombre: 'Sagrada Familia', regionId: 7 },
  { comunaId: 124, nombre: 'Teno', regionId: 7 },
  { comunaId: 125, nombre: 'Vichuquén', regionId: 7 },
  { comunaId: 126, nombre: 'Linares', regionId: 7 },
  { comunaId: 127, nombre: 'Colbún', regionId: 7 },
  { comunaId: 128, nombre: 'Longaví', regionId: 7 },
  { comunaId: 129, nombre: 'Parral', regionId: 7 },
  { comunaId: 130, nombre: 'Retiro', regionId: 7 },
  { comunaId: 131, nombre: 'San Javier', regionId: 7 },
  { comunaId: 132, nombre: 'Villa Alegre', regionId: 7 },
  { comunaId: 133, nombre: 'Yerbas Buenas', regionId: 7 },

  // Región del Biobío (8)
  { comunaId: 134, nombre: 'Concepción', regionId: 8 },
  { comunaId: 135, nombre: 'Coronel', regionId: 8 },
  { comunaId: 136, nombre: 'Chiguayante', regionId: 8 },
  { comunaId: 137, nombre: 'Florida', regionId: 8 },
  { comunaId: 138, nombre: 'Hualpén', regionId: 8 },
  { comunaId: 139, nombre: 'Hualqui', regionId: 8 },
  { comunaId: 140, nombre: 'Lota', regionId: 8 },
  { comunaId: 141, nombre: 'Penco', regionId: 8 },
  { comunaId: 142, nombre: 'San Pedro de la Paz', regionId: 8 },
  { comunaId: 143, nombre: 'Santa Juana', regionId: 8 },
  { comunaId: 144, nombre: 'Talcahuano', regionId: 8 },
  { comunaId: 145, nombre: 'Tomé', regionId: 8 },
  { comunaId: 146, nombre: 'Cabrero', regionId: 8 },
  { comunaId: 147, nombre: 'Laja', regionId: 8 },
  { comunaId: 148, nombre: 'Los Ángeles', regionId: 8 },
  { comunaId: 149, nombre: 'Mulchén', regionId: 8 },
  { comunaId: 150, nombre: 'Nacimiento', regionId: 8 },
  { comunaId: 151, nombre: 'Negrete', regionId: 8 },
  { comunaId: 152, nombre: 'Quilaco', regionId: 8 },
  { comunaId: 153, nombre: 'Quilleco', regionId: 8 },
  { comunaId: 154, nombre: 'San Rosendo', regionId: 8 },
  { comunaId: 155, nombre: 'Santa Bárbara', regionId: 8 },
  { comunaId: 156, nombre: 'Tucapel', regionId: 8 },
  { comunaId: 157, nombre: 'Yumbel', regionId: 8 },
  { comunaId: 158, nombre: 'Alto Biobío', regionId: 8 },
  { comunaId: 159, nombre: 'Arauco', regionId: 8 },
  { comunaId: 160, nombre: 'Cañete', regionId: 8 },
  { comunaId: 161, nombre: 'Contulmo', regionId: 8 },
  { comunaId: 162, nombre: 'Curanilahue', regionId: 8 },
  { comunaId: 163, nombre: 'Lebu', regionId: 8 },
  { comunaId: 164, nombre: 'Los Álamos', regionId: 8 },
  { comunaId: 165, nombre: 'Tirúa', regionId: 8 },

  // Región de La Araucanía (9)
  { comunaId: 166, nombre: 'Temuco', regionId: 9 },
  { comunaId: 167, nombre: 'Carahue', regionId: 9 },
  { comunaId: 168, nombre: 'Cunco', regionId: 9 },
  { comunaId: 169, nombre: 'Curarrehue', regionId: 9 },
  { comunaId: 170, nombre: 'Freire', regionId: 9 },
  { comunaId: 171, nombre: 'Galvarino', regionId: 9 },
  { comunaId: 172, nombre: 'Gorbea', regionId: 9 },
  { comunaId: 173, nombre: 'Lautaro', regionId: 9 },
  { comunaId: 174, nombre: 'Loncoche', regionId: 9 },
  { comunaId: 175, nombre: 'Melipeuco', regionId: 9 },
  { comunaId: 176, nombre: 'Nueva Imperial', regionId: 9 },
  { comunaId: 177, nombre: 'Padre Las Casas', regionId: 9 },
  { comunaId: 178, nombre: 'Perquenco', regionId: 9 },
  { comunaId: 179, nombre: 'Pitrufquén', regionId: 9 },
  { comunaId: 180, nombre: 'Pucón', regionId: 9 },
  { comunaId: 181, nombre: 'Saavedra', regionId: 9 },
  { comunaId: 182, nombre: 'Teodoro Schmidt', regionId: 9 },
  { comunaId: 183, nombre: 'Toltén', regionId: 9 },
  { comunaId: 184, nombre: 'Vilcún', regionId: 9 },
  { comunaId: 185, nombre: 'Villarrica', regionId: 9 },
  { comunaId: 186, nombre: 'Angol', regionId: 9 },
  { comunaId: 187, nombre: 'Collipulli', regionId: 9 },
  { comunaId: 188, nombre: 'Curacautín', regionId: 9 },
  { comunaId: 189, nombre: 'Ercilla', regionId: 9 },
  { comunaId: 190, nombre: 'Lonquimay', regionId: 9 },
  { comunaId: 191, nombre: 'Los Sauces', regionId: 9 },
  { comunaId: 192, nombre: 'Lumaco', regionId: 9 },
  { comunaId: 193, nombre: 'Purén', regionId: 9 },
  { comunaId: 194, nombre: 'Renaico', regionId: 9 },
  { comunaId: 195, nombre: 'Traiguén', regionId: 9 },
  { comunaId: 196, nombre: 'Victoria', regionId: 9 },

  // Región de Los Lagos (10)
  { comunaId: 197, nombre: 'Puerto Montt', regionId: 10 },
  { comunaId: 198, nombre: 'Calbuco', regionId: 10 },
  { comunaId: 199, nombre: 'Cochamó', regionId: 10 },
  { comunaId: 200, nombre: 'Fresia', regionId: 10 },
  { comunaId: 201, nombre: 'Frutillar', regionId: 10 },
  { comunaId: 202, nombre: 'Los Muermos', regionId: 10 },
  { comunaId: 203, nombre: 'Llanquihue', regionId: 10 },
  { comunaId: 204, nombre: 'Maullín', regionId: 10 },
  { comunaId: 205, nombre: 'Puerto Varas', regionId: 10 },
  { comunaId: 206, nombre: 'Castro', regionId: 10 },
  { comunaId: 207, nombre: 'Ancud', regionId: 10 },
  { comunaId: 208, nombre: 'Chonchi', regionId: 10 },
  { comunaId: 209, nombre: 'Curaco de Vélez', regionId: 10 },
  { comunaId: 210, nombre: 'Dalcahue', regionId: 10 },
  { comunaId: 211, nombre: 'Puqueldón', regionId: 10 },
  { comunaId: 212, nombre: 'Queilén', regionId: 10 },
  { comunaId: 213, nombre: 'Quellón', regionId: 10 },
  { comunaId: 214, nombre: 'Quemchi', regionId: 10 },
  { comunaId: 215, nombre: 'Quinchao', regionId: 10 },
  { comunaId: 216, nombre: 'Osorno', regionId: 10 },
  { comunaId: 217, nombre: 'Puerto Octay', regionId: 10 },
  { comunaId: 218, nombre: 'Purranque', regionId: 10 },
  { comunaId: 219, nombre: 'Puyehue', regionId: 10 },
  { comunaId: 220, nombre: 'Río Negro', regionId: 10 },
  { comunaId: 221, nombre: 'San Juan de la Costa', regionId: 10 },
  { comunaId: 222, nombre: 'San Pablo', regionId: 10 },
  { comunaId: 223, nombre: 'Chaitén', regionId: 10 },
  { comunaId: 224, nombre: 'Futaleufú', regionId: 10 },
  { comunaId: 225, nombre: 'Hualaihué', regionId: 10 },
  { comunaId: 226, nombre: 'Palena', regionId: 10 },

  // Región Aysén (11)
  { comunaId: 227, nombre: 'Coyhaique', regionId: 11 },
  { comunaId: 228, nombre: 'Lago Verde', regionId: 11 },
  { comunaId: 229, nombre: 'Aysén', regionId: 11 },
  { comunaId: 230, nombre: 'Cisnes', regionId: 11 },
  { comunaId: 231, nombre: 'Guaitecas', regionId: 11 },
  { comunaId: 232, nombre: 'Cochrane', regionId: 11 },
  { comunaId: 233, nombre: 'O\'Higgins', regionId: 11 },
  { comunaId: 234, nombre: 'Tortel', regionId: 11 },
  { comunaId: 235, nombre: 'Chile Chico', regionId: 11 },
  { comunaId: 236, nombre: 'Río Ibáñez', regionId: 11 },

  // Región de Magallanes (12)
  { comunaId: 237, nombre: 'Punta Arenas', regionId: 12 },
  { comunaId: 238, nombre: 'Laguna Blanca', regionId: 12 },
  { comunaId: 239, nombre: 'Río Verde', regionId: 12 },
  { comunaId: 240, nombre: 'San Gregorio', regionId: 12 },
  { comunaId: 241, nombre: 'Cabo de Hornos', regionId: 12 },
  { comunaId: 242, nombre: 'Antártica', regionId: 12 },
  { comunaId: 243, nombre: 'Porvenir', regionId: 12 },
  { comunaId: 244, nombre: 'Primavera', regionId: 12 },
  { comunaId: 245, nombre: 'Timaukel', regionId: 12 },
  { comunaId: 246, nombre: 'Natales', regionId: 12 },
  { comunaId: 247, nombre: 'Torres del Paine', regionId: 12 },

  // Región Metropolitana (13)
  { comunaId: 248, nombre: 'Cerrillos', regionId: 13 },
  { comunaId: 249, nombre: 'Cerro Navia', regionId: 13 },
  { comunaId: 250, nombre: 'Conchalí', regionId: 13 },
  { comunaId: 251, nombre: 'El Bosque', regionId: 13 },
  { comunaId: 252, nombre: 'Estación Central', regionId: 13 },
  { comunaId: 253, nombre: 'Huechuraba', regionId: 13 },
  { comunaId: 254, nombre: 'Independencia', regionId: 13 },
  { comunaId: 255, nombre: 'La Cisterna', regionId: 13 },
  { comunaId: 256, nombre: 'La Florida', regionId: 13 },
  { comunaId: 257, nombre: 'La Granja', regionId: 13 },
  { comunaId: 258, nombre: 'La Pintana', regionId: 13 },
  { comunaId: 259, nombre: 'La Reina', regionId: 13 },
  { comunaId: 260, nombre: 'Las Condes', regionId: 13 },
  { comunaId: 261, nombre: 'Lo Barnechea', regionId: 13 },
  { comunaId: 262, nombre: 'Lo Espejo', regionId: 13 },
  { comunaId: 263, nombre: 'Lo Prado', regionId: 13 },
  { comunaId: 264, nombre: 'Macul', regionId: 13 },
  { comunaId: 265, nombre: 'Maipú', regionId: 13 },
  { comunaId: 266, nombre: 'Ñuñoa', regionId: 13 },
  { comunaId: 267, nombre: 'Pedro Aguirre Cerda', regionId: 13 },
  { comunaId: 268, nombre: 'Peñalolén', regionId: 13 },
  { comunaId: 269, nombre: 'Providencia', regionId: 13 },
  { comunaId: 270, nombre: 'Pudahuel', regionId: 13 },
  { comunaId: 271, nombre: 'Quilicura', regionId: 13 },
  { comunaId: 272, nombre: 'Quinta Normal', regionId: 13 },
  { comunaId: 273, nombre: 'Recoleta', regionId: 13 },
  { comunaId: 274, nombre: 'Renca', regionId: 13 },
  { comunaId: 275, nombre: 'San Joaquín', regionId: 13 },
  { comunaId: 276, nombre: 'San Miguel', regionId: 13 },
  { comunaId: 277, nombre: 'San Ramón', regionId: 13 },
  { comunaId: 278, nombre: 'Santiago', regionId: 13 },
  { comunaId: 279, nombre: 'Vitacura', regionId: 13 },
  { comunaId: 280, nombre: 'Puente Alto', regionId: 13 },
  { comunaId: 281, nombre: 'Pirque', regionId: 13 },
  { comunaId: 282, nombre: 'San José de Maipo', regionId: 13 },
  { comunaId: 283, nombre: 'Colina', regionId: 13 },
  { comunaId: 284, nombre: 'Lampa', regionId: 13 },
  { comunaId: 285, nombre: 'Tiltil', regionId: 13 },
  { comunaId: 286, nombre: 'San Bernardo', regionId: 13 },
  { comunaId: 287, nombre: 'Buin', regionId: 13 },
  { comunaId: 288, nombre: 'Calera de Tango', regionId: 13 },
  { comunaId: 289, nombre: 'Paine', regionId: 13 },
  { comunaId: 290, nombre: 'Melipilla', regionId: 13 },
  { comunaId: 291, nombre: 'Alhué', regionId: 13 },
  { comunaId: 292, nombre: 'Curacaví', regionId: 13 },
  { comunaId: 293, nombre: 'María Pinto', regionId: 13 },
  { comunaId: 294, nombre: 'San Pedro', regionId: 13 },
  { comunaId: 295, nombre: 'Talagante', regionId: 13 },
  { comunaId: 296, nombre: 'El Monte', regionId: 13 },
  { comunaId: 297, nombre: 'Isla de Maipo', regionId: 13 },
  { comunaId: 298, nombre: 'Padre Hurtado', regionId: 13 },
  { comunaId: 299, nombre: 'Peñaflor', regionId: 13 },

  // Región de Los Ríos (14)
  { comunaId: 300, nombre: 'Valdivia', regionId: 14 },
  { comunaId: 301, nombre: 'Corral', regionId: 14 },
  { comunaId: 302, nombre: 'Lanco', regionId: 14 },
  { comunaId: 303, nombre: 'Los Lagos', regionId: 14 },
  { comunaId: 304, nombre: 'Máfil', regionId: 14 },
  { comunaId: 305, nombre: 'Mariquina', regionId: 14 },
  { comunaId: 306, nombre: 'Paillaco', regionId: 14 },
  { comunaId: 307, nombre: 'Panguipulli', regionId: 14 },
  { comunaId: 308, nombre: 'La Unión', regionId: 14 },
  { comunaId: 309, nombre: 'Futrono', regionId: 14 },
  { comunaId: 310, nombre: 'Lago Ranco', regionId: 14 },
  { comunaId: 311, nombre: 'Río Bueno', regionId: 14 },
  { comunaId: 312, nombre: 'Arica', regionId: 15 },
  { comunaId: 313, nombre: 'Camarones', regionId: 15 },
  { comunaId: 314, nombre: 'Putre', regionId: 15 },
  { comunaId: 315, nombre: 'General Lagos', regionId: 15 },
  { comunaId: 316, nombre: 'Chillán', regionId: 16 },
  { comunaId: 317, nombre: 'Chillán Viejo', regionId: 16 },
  { comunaId: 318, nombre: 'Cobquecura', regionId: 16 },
  { comunaId: 319, nombre: 'Coelemu', regionId: 16 },
  { comunaId: 320, nombre: 'Coihueco', regionId: 16 },
  { comunaId: 321, nombre: 'El Carmen', regionId: 16 },
  { comunaId: 322, nombre: 'Ninhue', regionId: 16 },
  { comunaId: 323, nombre: 'Ñiquén', regionId: 16 },
  { comunaId: 324, nombre: 'Pemuco', regionId: 16 },
  { comunaId: 325, nombre: 'Pinto', regionId: 16 },
  { comunaId: 326, nombre: 'Portezuelo', regionId: 16 },
  { comunaId: 327, nombre: 'Quillón', regionId: 16 },
  { comunaId: 328, nombre: 'Quirihue', regionId: 16 },
  { comunaId: 329, nombre: 'Ránquil', regionId: 16 },
  { comunaId: 330, nombre: 'San Carlos', regionId: 16 },
  { comunaId: 331, nombre: 'San Fabián', regionId: 16 },
  { comunaId: 332, nombre: 'San Ignacio', regionId: 16 },
  { comunaId: 333, nombre: 'San Nicolás', regionId: 16 },
  { comunaId: 334, nombre: 'Treguaco', regionId: 16 },
  { comunaId: 335, nombre: 'Yungay', regionId: 16 },
]; 